services:
  postgres:
    image: postgres:14-alpine
    container_name: test-db
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test
    volumes:
      - ./init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
      - ./local/postgres:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: unless-stopped

  backend:
    image: node:14.17.6
    container_name: test-api
    command: sh -c
      "yarn &&
       npm install -g @nestjs/cli &&
       yarn start:dev"
    working_dir: /app
    ports:
      - "4000:4000"
    depends_on:
      postgres:
        condition: service_started
    volumes:
      - ./data/init.sql:/docker-entrypoint-initdb.d/init.sql
      - .:/app
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 5454:5454/tcp
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mydomain.com
      - PGADMIN_DEFAULT_PASSWORD=postgres
      - PGADMIN_LISTEN_PORT=5454
    links:
      - postgres

volumes:
  postgres_data:
